Ssl credentials test
devsu/condor-framework pull request #11
Opened 2017-01-24 21:55 UTC by jdgutierrez

Implement test for ssl credentials and call credentials

2017-01-24 21:59 UTC, c3s4r requested changes

2017-01-24 21:59 UTC, c3s4r commented on lib/server.spec.js
> +      server = new Server(builder, {'creds': combineCreds});
Desde fuera debe recibirse dos parámetros en las opciones: creds, y callCredentials, y deben combinarse dentro del server.

2017-01-25 15:14 UTC, c3s4r commented on README.md
> +  'creds': grpc.ServerCredentials.createSsl(new Buffer('rootCert'), [
No se si sería buena idea más bien pasar:

```js
options = {
  'rootCert': new Buffer('rootCert'),
  'certChain': new Buffer('cert_chain'),
  'privateKey': new Buffer('private_ley');
}
```

o mejor aún:

```js
options = {
  'rootCertPath': '/path/to/my/root/cert',
  'certChain': '/path/to/my/cert/chain/folder',
  'privateKey': 'my-private-key-as-string',
}
```

Porqué hago esta propuesta? Creo que en general nuestro módulo debería ser un wrapper de gRPC, y no creo que sea buena idea que tengan que usar el módulo grpc para generar el certificado, cuando podríamos hacerlo dentro del módulo.

Esto obviamente va a requerir una investigación de cómo funcionan los certificados. (Se podría trabajar esto con Yonel).

2017-01-25 20:19 UTC, c3s4r commented on lib/server.js
> +  _areSslOptions(options) {
El nombre del método no me gusta. Sería mejor _hasSslOptions?

2017-01-25 20:19 UTC, c3s4r commented on spec/ssl/ca.pem
> +-----BEGIN CERTIFICATE-----
Este no es un certificado real, o si?

2017-01-25 20:19 UTC, c3s4r commented on README.md
> +  'rootCert': '/path/to/root/cert',
Nada más por confirmar, los 3 elementos vienen generalmente en 3 archivos diferentes, cada uno en un solo archivo?

2017-01-25 20:25 UTC, jdgutierrez commented on spec/ssl/ca.pem
> +-----BEGIN CERTIFICATE-----
Sí, es un certificado real que habia generado para las pruebas de integración

2017-01-25 20:27 UTC, jdgutierrez commented on README.md
> +  'rootCert': '/path/to/root/cert',
Sí, todos son archivos generados por openssl

2017-01-25 21:16 UTC, jdgutierrez commented
Talking with Yonel, he showed me his ssl examples and determined that rootCerts is not an option required but only certChain and privateKey

2017-01-26 16:23 UTC, c3s4r requested changes

2017-01-26 16:23 UTC, c3s4r commented on lib/server.js
> +      throw new Error('Cannot perform operation: Ssl certificate files not found');
Algo pequeño, talvez en el error mostrar el path del archivo que no existe?

```
throw new Error(`Cannot perform operation: File not found ${path}`);
```

2017-01-26 16:23 UTC, c3s4r commented on lib/server.js
> +      throw new Error('Cannot perform operation: Ssl certificate files not found');
Esto mas que nada es útil para el developer para saber a cuál archivo exactamente se está refiriendo.

2017-01-26 16:23 UTC, c3s4r commented on README.md
> +  'rootCert': '/path/to/root/cert',
Una cosa más, talvez poner la extensión del archivo, más que nada para ayudarle al developer a identificar más fácilmente el archivo que corresponde a cada variable?

2017-01-26 16:23 UTC, c3s4r commented on spec/ssl/ca.pem
> +-----BEGIN CERTIFICATE-----
Asegurémonos que el certificado subido corresponda a un URL de ejemplo que podamos usar para las pruebas. Por ejemplo: myservice.example.com?

2017-01-26 22:36 UTC, merged